{{
    config(materialized='view')
}}


WITH src_orders AS (
    SELECT
    *
    FROM {{source('sql_server_dbo','orders')}}
)

SELECT
ORDER_ID,
MD5(INITCAP(SHIPPING_SERVICE)) AS SHIPPING_SERVICE_ID,
COALESCE(SHIPPING_COST,0) AS SHIPPING_COST,
ADDRESS_ID,
CONVERT_TIMEZONE('UTC',CREATED_AT) AS CREATED_AT,
CASE
WHEN PROMO_ID = '' THEN MD5('No promo')
ELSE MD5(PROMO_ID)
END AS PROMO_ID,
CONVERT_TIMEZONE('UTC',ESTIMATED_DELIVERY_AT) AS ESTIMATED_DELIVERY_AT,
COALESCE(ORDER_COST,0) AS ORDER_COST,
ORDER_TOTAL,
CONVERT_TIMEZONE('UTC',DELIVERED_AT) AS DELIVERED_AT,
NULLIF(TRACKING_ID,'') AS TRACKING_ID,
STATUS,
_FIVETRAN_DELETED,
CONVERT_TIMEZONE('UTC',_FIVETRAN_SYNCED) AS _FIVETRAN_SYNCED 
FROM src_orders
WHERE _FIVETRAN_DELETED IS NULL

